### ISSUE TITLE
How do i get packages back? 

### ISSUE THREAD

**Issue by SimonGSGmbH** [yireo/magento2-replace-tools#3]
I´ve installed yireo/magento2-replace-core and by that         
"magento/module-advanced-pricing-import-export": "^100.4",
"magento/module-bundle-import-export": "^100.4",
"magento/module-configurable-import-export": "^100.4",
"magento/module-customer-import-export": "^100.4",
"magento/module-downloadable-import-export": "^100.4",
"magento/module-grouped-import-export": "^100.4"

are removed. How do i get them back working?

**Comment by jissereitsma** [comment]
You can't. If you don't want to remove those packages, remove the package `yireo/magento2-replace-core`. Next, inspect the `composer.json` file of this package in the right branch and copy the `replace` rules that you do want.

**Comment by SimonGSGmbH** [comment]
Ok, but i will never be able to add "magento/module-downloadable-import-export" again in that install?

**Comment by jissereitsma** [comment]
I don't understand. If you are using the `yireo/magento2-replace-core` package to deliberately remove the `magento/module-downloadable-import-export` package, there is **no** such a thing as un-removal. Simply don't use this meta-package but copy the same rules in your own composer configuration. Note that this `yireo/magento2-replace-core` is not meant to be a no-brains solution. Instead, it is a proof-of-concept that you skin down the core. But numerous devs are only using it is a reference for their own manual replacements, exactly because of the issue that you address.

**Comment by SimonGSGmbH** [comment]
Ok i see. Not your fault, thought that there is a way... 
Didnt see the import-export in that replacements, weeks ago... So now i cannot install 3rd party Modules cause of that... 
Than i have to start over...

**Comment by jissereitsma** [comment]
:) No worries. It is sometimes but a bit more work, but it allows you to squeeze the maximum out of performance.

**Comment by SimonGSGmbH** [comment]
Package is absolutely nice, no question! As i said, my fault. Thanks for your help!

**Comment by SimonGSGmbH** [comment]
found a way:

install manually in app/code. works for me now. 
but surely not the mentoined way... ;-)
