### ISSUE TITLE
Question: coexistance of graphql and inventory replace

### ISSUE THREAD

**Issue by onepack** [yireo/magento2-replace-tools#5]
I installed the graphql removal and after that I was not able to install the inventory removal as there was a conflict.

- yireo/magento2-replace-inventory[4.2.0, ..., 4.2.5] cannot be installed as that would require removing yireo/magento2-replace-graphql[4.2.5]. They all replace magento/module-inventory-graph-ql and thus cannot coexist.

Is it an idea to strip the magento/module-inventory-graph-ql from the graphql list so they can coexist?

**Comment by jissereitsma** [comment]
Unfortunately, removing `magento/module-inventory-graph-ql` from the GraphQL replacements is going to break that GraphQL replacement because the code in that package is depending on the other removed GraphQL code.

This conflict is a known issue. The only solution here is to copy the replacements to your own projects `composer.json` file.

**Comment by onepack** [comment]
Yeah, that's what I did in the end. Thanks for your feedback.
